export let movies=[
    {
          title: "Bahubali",
          plot: "Bahubali is a movie set in and around the fictional kingdom of Mahishmati.",
          price: 200,
          poster: "https://www.filmibeat.com/ph-big/2017/05/baahubali-2-the-conclusion_149577721640.jpg",
          rating: 8.5,
          star: 0,
          fav: false,
          isIncart: false,
        },
        {
          title: "Bahubali",
          plot: "Bahubali is a movie set in and around the fictional kingdom of Mahishmati.",
          price: 250,
          poster: "https://www.filmibeat.com/ph-big/2017/05/baahubali-2-the-conclusion_149577721640.jpg",
          rating: 8.5,
          star: 0,
          fav: false,
          isIncart: false,
        },
        {
          title: "Bahubali",
          plot: "Bahubali is a movie set in and around the fictional kingdom of Mahishmati.",
          price: 250,
          poster: "https://www.filmibeat.com/ph-big/2017/05/baahubali-2-the-conclusion_149577721640.jpg",
          rating: 8.5,
          star: 0,
          fav: false,
          isIncart: false,
        },
        {
          title: "Bahubali",
          plot: "Bahubali is a movie set in and around the fictional kingdom of Mahishmati.",
          price: 250,
          poster: "https://www.filmibeat.com/ph-big/2017/05/baahubali-2-the-conclusion_149577721640.jpg",
          rating: 8.5,
          star: 0,
          fav: false,
          isIncart: false,
        },
]